### ISSUE TITLE
What does dynamic map mean?

### ISSUE THREAD

**Issue by youngsuen** [yjlolo/gmvae-synth#1]
dynamic_map = {
    'f': 0,
    'ff': 1,
    'mf': 2,
    'p': 3,
    'pp': 4
}

**Comment by yjlolo** [comment]
This is to leverage the dynamic labels from the dataset, so that we can later check whether the timbre space is also clustered according to the dynamic, which is the case if you play with the following interactive website.

https://timbre-vis.herokuapp.com/
This demonstrates the learned timbre space, which you can play with 

- different color scheme including dynamic
- drag to view the space with different angles
- hover on points and listen (with a bit latency)

You can safely delete the dictionary because it is not necessary for training.

**Comment by yjlolo** [comment]
Closing with no further doubts.
